// <auto-generated />
using System;
using FitnessTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Infrastructure.Migrations
{
    [DbContext(typeof(FitnessTrackerDbContext))]
    partial class FitnessTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Core.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<double?>("AvgHeartRate")
                        .HasColumnType("float");

                    b.Property<double?>("AvgPaceSecPerKm")
                        .HasColumnType("float");

                    b.Property<double?>("AvgPowerWatts")
                        .HasColumnType("float");

                    b.Property<double?>("AvgSpeedKph")
                        .HasColumnType("float");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("ElapsedTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("MaxHeartRate")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("MovingTime")
                        .HasColumnType("time");

                    b.Property<double?>("NormalizedPowerWatts")
                        .HasColumnType("float");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<double?>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<double?>("TotalElevationGainMeters")
                        .HasColumnType("float");

                    b.Property<double?>("TrainingLoad")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "StartTimeUtc", "Sport");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FitnessTracker.Core.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("FitnessTracker.Core.Models.Threshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FtpWatts")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<double?>("ThresholdPaceSecPerKm")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId", "Sport", "EffectiveDate");

                    b.ToTable("Thresholds");
                });

            modelBuilder.Entity("FitnessTracker.Core.Models.Activity", b =>
                {
                    b.HasOne("FitnessTracker.Core.Models.Athlete", "Athlete")
                        .WithMany("Activities")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("FitnessTracker.Core.Models.Threshold", b =>
                {
                    b.HasOne("FitnessTracker.Core.Models.Athlete", "Athlete")
                        .WithMany("Thresholds")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("FitnessTracker.Core.Models.Athlete", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Thresholds");
                });
#pragma warning restore 612, 618
        }
    }
}
